services:
  - type: web
    name: exe-vnc-server
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: VNC_PASSWORD
        value: StrongPassword123
      - key: DISPLAY
        value: ":0"
